apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: fe
          servicePort: 80
      - path: /api/nameday
        backend:
          serviceName: be
          servicePort: 80
