apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: be
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  http:
  - match:
    - uri:
        prefix: /api/nameday
    route:
    - destination:
        host: be
        subset: v1
      weight: 90
    - destination:
        host: be
        subset: v2
      weight: 10

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fe
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: fe
        subset: v1
